/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.31 from the
 * contents of Apophenia.xs. Do not edit this file, edit Apophenia.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Apophenia.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "apop.h"
#include "stdio.h"


double sum(AV* array)
{
  int i;
  double sum = 0.0;
  int av_length = av_len(array) +1;
  gsl_vector* v = gsl_vector_alloc(av_length);
  for (i = 0; i < av_length; i++) {
      SV** elem = av_fetch(array, i, 0);
      gsl_vector_set(v, i, SvNV(*elem));
    }
  sum = apop_vector_sum(v);
  gsl_vector_free (v);
  return sum;
}

double mean(AV* array)
{
  int i;
  double mean= 0.0;
  int av_length = av_len(array) +1;
  gsl_vector* v = gsl_vector_alloc(av_length);
  for (i = 0; i < av_length; i++) {
      SV** elem = av_fetch(array, i, 0);
      gsl_vector_set(v, i, SvNV(*elem));
    }
  mean = apop_vector_mean(v);
  gsl_vector_free (v);
  return mean;
}
double var(AV* array)
{
  int i;
  double var= 0.0;
  int av_length = av_len(array) +1;
  gsl_vector* v = gsl_vector_alloc(av_length);
  for (i = 0; i < av_length; i++) {
      SV** elem = av_fetch(array, i, 0);
      gsl_vector_set(v, i, SvNV(*elem));
    }
  var = apop_vector_var(v);
  gsl_vector_free (v);
  return var;
}

double skew(AV* array)
{
  int i;
  double skew= 0.0;
  int av_length = av_len(array) +1;
  gsl_vector* v = gsl_vector_alloc(av_length);
  for (i = 0; i < av_length; i++) {
      SV** elem = av_fetch(array, i, 0);
      gsl_vector_set(v, i, SvNV(*elem));
    }
  skew = apop_vector_skew(v);
  gsl_vector_free (v);
  return skew;
}
double kurtosis(AV* array)
{
  int i;
  double kurtosis= 0.0;
  int av_length = av_len(array) +1;
  gsl_vector* v = gsl_vector_alloc(av_length);
  for (i = 0; i < av_length; i++) {
      SV** elem = av_fetch(array, i, 0);
      gsl_vector_set(v, i, SvNV(*elem));
    }
  kurtosis = apop_vector_kurtosis(v);
  gsl_vector_free (v);
  return kurtosis;
}


AV* t_test_arr(AV* l, AV* r) {
  int i;
  // init gsl_vector l
  int av_l_length = av_len(l) +1;
  gsl_vector* v_l = gsl_vector_alloc(av_l_length);
  for (i = 0; i < av_l_length; i++) {
      SV** elem = av_fetch(l, i, 0);
      gsl_vector_set(v_l, i, SvNV(*elem));
  }

  // init gsl_vector r
  int av_r_length = av_len(r) +1;
  gsl_vector* v_r = gsl_vector_alloc(av_r_length);
  for (i = 0; i < av_r_length; i++) {
      SV** elem = av_fetch(r, i, 0);
      gsl_vector_set(v_r, i, SvNV(*elem));
  }
  apop_data *test_out = apop_t_test(v_l, v_r);
/*
   apop_data_add_named_elmt(out, "mean left - right", diff);
   apop_data_add_named_elmt(out, "t statistic", stat);
   apop_data_add_named_elmt(out, "df", df);
   apop_data_add_named_elmt(out, "p value, 1 tail", GSL_MIN(pval,qval));
   apop_data_add_named_elmt(out, "confidence, 1 tail", 1 - GSL_MIN(pval,qval));
   apop_data_add_named_elmt(out, "p value, 2 tail", 1- two_tail);
   apop_data_add_named_elmt(out, "confidence, 2 tail", two_tail);
*/
   double diff = apop_data_get(test_out, .rowname="mean left - right");
   double t_stat = apop_data_get(test_out, .rowname="t statistic");
   double df  = apop_data_get(test_out, .rowname="df");
   double p_value_1_tail  = apop_data_get(test_out, .rowname="p value, 1 tail");
   double one_tail = apop_data_get(test_out, .rowname="confidence, 1 tail");
   double p_value_2_tail  = apop_data_get(test_out, .rowname="p value, 2 tail");
   double two_tail = apop_data_get(test_out, .rowname="confidence, 1 tail");
   AV* av= newAV();
   sv_2mortal((SV*)av);
   av_store(av,0, newSVnv(diff));
   av_store(av,1, newSVnv(t_stat));
   av_store(av,2, newSVnv(df));
   av_store(av,3, newSVnv(p_value_1_tail));
   av_store(av,4, newSVnv(one_tail));
   av_store(av,5, newSVnv(p_value_2_tail));
   av_store(av,6, newSVnv(two_tail));
   return av;

  /*int rv_size = test_out_vector->size;
  AV* av= newAV();
  sv_2mortal((SV*)av);
  for (i = 0; i < rv_size; i++)
    {
      av_store(av,i, newSVnv(gsl_vector_get(test_out_vector, i)));
    }
*/
    
  //TODO: return app_data outcome vector and then write perl wrapper
}



#line 155 "Apophenia.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 299 "Apophenia.c"

XS_EUPXS(XS_Apophenia_sum); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Apophenia_sum)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "array");
    {
	AV *	array;
	double	RETVAL;
	dXSTARG;

	STMT_START {
		SV* const xsub_tmp_sv = ST(0);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    array = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not an ARRAY reference",
				"Apophenia::sum",
				"array");
		}
	} STMT_END
;

	RETVAL = sum(array);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Apophenia_mean); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Apophenia_mean)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "array");
    {
	AV *	array;
	double	RETVAL;
	dXSTARG;

	STMT_START {
		SV* const xsub_tmp_sv = ST(0);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    array = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not an ARRAY reference",
				"Apophenia::mean",
				"array");
		}
	} STMT_END
;

	RETVAL = mean(array);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Apophenia_var); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Apophenia_var)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "array");
    {
	AV *	array;
	double	RETVAL;
	dXSTARG;

	STMT_START {
		SV* const xsub_tmp_sv = ST(0);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    array = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not an ARRAY reference",
				"Apophenia::var",
				"array");
		}
	} STMT_END
;

	RETVAL = var(array);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Apophenia_skew); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Apophenia_skew)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "array");
    {
	AV *	array;
	double	RETVAL;
	dXSTARG;

	STMT_START {
		SV* const xsub_tmp_sv = ST(0);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    array = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not an ARRAY reference",
				"Apophenia::skew",
				"array");
		}
	} STMT_END
;

	RETVAL = skew(array);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Apophenia_kurtosis); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Apophenia_kurtosis)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "array");
    {
	AV *	array;
	double	RETVAL;
	dXSTARG;

	STMT_START {
		SV* const xsub_tmp_sv = ST(0);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    array = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not an ARRAY reference",
				"Apophenia::kurtosis",
				"array");
		}
	} STMT_END
;

	RETVAL = kurtosis(array);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Apophenia_t_test_arr); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Apophenia_t_test_arr)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "l, r");
    {
	AV*	l;
	AV*	r;
	AV *	RETVAL;

	STMT_START {
		SV* const xsub_tmp_sv = ST(0);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    l = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not an ARRAY reference",
				"Apophenia::t_test_arr",
				"l");
		}
	} STMT_END
;

	STMT_START {
		SV* const xsub_tmp_sv = ST(1);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    r = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not an ARRAY reference",
				"Apophenia::t_test_arr",
				"r");
		}
	} STMT_END
;

	RETVAL = t_test_arr(l, r);
	{
	    SV * RETVALSV;
	    RETVALSV = newRV((SV*)RETVAL);
	    RETVALSV = sv_2mortal(RETVALSV);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Apophenia); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Apophenia)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Apophenia::sum", XS_Apophenia_sum);
        newXS_deffile("Apophenia::mean", XS_Apophenia_mean);
        newXS_deffile("Apophenia::var", XS_Apophenia_var);
        newXS_deffile("Apophenia::skew", XS_Apophenia_skew);
        newXS_deffile("Apophenia::kurtosis", XS_Apophenia_kurtosis);
        newXS_deffile("Apophenia::t_test_arr", XS_Apophenia_t_test_arr);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

