# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package Apophenia::Stat;
use base qw(Exporter);
use base qw(DynaLoader);
package Apophenia::Statc;
bootstrap Apophenia::Stat;
package Apophenia::Stat;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package Apophenia::Stat;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Apophenia::Stat;

*apop_vector_log = *Apophenia::Statc::apop_vector_log;
*apop_vector_sum = *Apophenia::Statc::apop_vector_sum;

# ------- VARIABLE STUBS --------

package Apophenia::Stat;

1;
